### ISSUE TITLE
angular-template-asset-pipeline 2.0.1 does not appear to be working

### ISSUE THREAD

**Issue by rbfinch** [craigburke/angular-template-asset-pipeline#12]
I have a simple test grails app that uses angular-template-asset-pipeline in Grails 2.4.4.  It works fine using the following versions in `BuildConfig.groovy`:

        compile ":asset-pipeline:1.9.9"
        compile ":angular-template-asset-pipeline:1.4.2"

But does not when using current versions:

        compile ":asset-pipeline:2.0.10"
        compile ":angular-template-asset-pipeline:2.0.1"

In 2.0.1, I do not see the JavaScript files generated by the plugin to cache the templates that should be included by a `require_tree` directive in my main JavaScript file.

**Comment by craigburke** [comment]
Looks like this is resolved with version 2.1.0 of the asset pipeline (both **tpl.htm** and **tpl.html** should now work).

**Comment by rbfinch** [comment]
I'm finally getting around to trying the new versions in my test app.  I updated `BuildConfig.groovy` to

    	compile ":asset-pipeline:2.1.0"
    	compile ":angular-template-asset-pipeline:2.0.3"

and did `grails refresh-dependencies`.  I'm still seeing the same behavior as before; the script tag loading the template isn't included with `require_tree` but is if I use an explicit require.

Is there something else I need to do?

**Comment by craigburke** [comment]
I don't think so. I'll have to take a look again. I was pretty sure this was fixed but I very well could be wrong.

**Comment by craigburke** [comment]
Yeah looks like the issue with .tpl.html is still there (workaround is to use .tpl.htm). I'll keep you posted on when that looks like its resolved in the asset pipeline core project.

**Comment by ctoestreich** [comment]
This is still an issue.  Can you update docs to say something about the html vs htm issue?

**Comment by craigburke** [comment]
@ctoestreich I thought I already removed all the references to _tpl.html_ (as opposed to _tpl.htm_) from the docs (let me know if I missed one).

Adding back support for _tpl.html_ will involve a change to the Asset pipeline core project. I know this one is on @davydotcom's radar already.

**Comment by ctoestreich** [comment]
@craigburke Yeah I am sure he is working on it.  I see that you have the "use tml.htm" on the docs, but I think it needs to be explicit that the *html is broken atm.  I got tripped up as I was using your https://github.com/craigburke/lazybones-angular-grails and more specifically https://github.com/craigburke/lazybones-angular-grails/tree/master/templates/angular-grails/grails-app/assets/vendor/grails/templates/directives as a reference for a grails angular app and that still has html as the file extension.

**Comment by craigburke** [comment]
@ctoestreich yeah, that's a good idea. I've made the change to the docs.

**Comment by craigburke** [comment]
@ctoestreich should work now if you use version 2.2.0 of the asset pipeline thanks to @davydotcom.
