### ISSUE TITLE
Plugin poping errors at runtime

### ISSUE THREAD

**Issue by kaione** [craigburke/angular-template-asset-pipeline#13]
WAR packaging error: No signature of method: static asset.pipeline.AssetHelper.getAssetPathsByPlugin() is applicable for argument types: () values: []

Here is the error that comes out when I build my server after adding the line runtime ":angular-template-asset-pipeline:2.0.3" to my BuildConfig.groovy file

**Comment by craigburke** [comment]
Are you using the most recent version of the asset pipeline plugin?

**Comment by kaione** [comment]
I am using 1.9.9, I tried to upgrade to 2.0.20 and 2.1.0 but the same error appears

**Comment by craigburke** [comment]
Could you paste your BuildConfig.groovy file here so I can see if anything jumps out at me.

**Comment by craigburke** [comment]
I think a `grails clean-all` will fix this for you. Feel free to reopen this issue if the problem persists.
