### ISSUE TITLE
Template file not being added to the cache

### ISSUE THREAD

**Issue by JCDubs** [craigburke/angular-template-asset-pipeline#18]
Hi Craig, I left a comment on your blog about my implementation of the templates plugin not working with my templates, my comment was:

> Hi Craig. I am currently attempting to implement a angular front end in to my grails applications following your example application and other examples that I have come across. I am using grails 2.4.3 and have tried using a number of versions of angular template and angular annotation plugin version but I have not been able to get it to work seamlessly.
> 
> The problem that I am having is with partial templates. I have followed all guidelines in the documentation regarding module names, template location and unique file names but whenever I try to reference a template in my directives I receive a 404 not found error for the template file I am referencing.
> 
> When I start the grails app the following is logged out which would suggest the templates are not being inserted into the cache:
> 
> Cache [:]
> Cache [:]
> Cache [:]
> 
> Also, when using the developer tools in chrome I notice that the asset directory does not contain the template directory I created to hold the template files.
> 
> Could you help?

The test application is on git hub at https://github.com/JCDubs/AngularGrails. It contains all of the files and the angular implementation for reference.

**Comment by craigburke** [comment]
Hi @JCDubs: give the following a try. Use **tpl.htm** instead of **tpl.html** (currently only the former is supported) but supporting both is on my list of issues to get resolved.

Also, since the path to the template file has to match the module name, I would move your tpl.htm file to /assets/javascripts/header-module/templates.

Does that help?

**Comment by JCDubs** [comment]
@craigburke, I tried your suggestions above but it didn't help. I tried placing the _test-header-template.tpl.htm_ file into the _assets/javascripts/header-module/templates/_ directory. I also tried placing the template file into the _assets/javascripts/directives/templates/_ directory as well but no joy. Im not sure what else could solve the problem.

**Comment by craigburke** [comment]
@JCDubs alright I'll pull the project and see if I can get it working.

**Comment by craigburke** [comment]
Hi @JCDubs take a look at my pull request, that appears to be working. When I browse to `http://localhost:8080/anggrails/assets/header-module/templates/test-header-template.js` 

I see this:

```
angular.module('headerModule').run(['$templateCache', function($templateCache) {
    $templateCache.put('test-header-template.htm', '<h1>The Template File Works</h1>');
}]);
```

**Comment by craigburke** [comment]
One thing to keep in mind is that the path that the templates are in matters. If you decide to use the plugin I'd recommend grouping your files by the module name instead of type of object.

```
/javascripts/module1/controllers.js
/javascripts/module2/controllers.js
```

instead of

```
/javascripts/controllers/module1.js
/javascripts/controllers/module2.js
```

**Comment by JCDubs** [comment]
Nice one @craigburke, I have merged your pull request and it works brilliantly. I will take your recommendations for structural standards forward in my angular development and I look forward to implementing angular in the front end of all of my apps, cheers.

**Comment by craigburke** [comment]
@JCDubs great! Happy to help! :smiley:
