### ISSUE TITLE
Templates do not work in Grails 3 Jar

### ISSUE THREAD

**Issue by bobbywarner** [craigburke/angular-template-asset-pipeline#19]
Create a new Grails 3 (latest snapshot, not RC1) sample project using Angular.js templates.  Then run `./gradlew assemble` to build a runnable Jar.  This Jar can be run in place `java -jar build/libs/sample-0.1.jar` and everything works, but if you copy the Jar to another location on your hard-drive, it will fail to run just for pages that use these Angular.js templates.

There was a very similar Grails 3 bug for GSPs recently: https://jira.grails.org/browse/GRAILS-12077

**Comment by craigburke** [comment]
Wow, that's an odd one. I'll dig into this one today.

**Comment by davydotcom** [comment]
whaaaa?

**Comment by davydotcom** [comment]
just one small thing for grails 3 aren't you supposed to be doing java -jar on the war file not the jar file?

**Comment by craigburke** [comment]
@davydotcom haven't checked with the latest snapshot yet but that does work with RC1.

I saw the same behavior @bobbywarner did running it against the jar file, but the war file worked fine no matter where it was. Is the jar file not a fat jar?

**Comment by davydotcom** [comment]
i think something is up with the jar file I'm not exactly sure what it is

**Comment by craigburke** [comment]
@davydotcom makes sense. @bobbywarner did you notice this issue using any AP plugin other than the AngularJS templates?

**Comment by davydotcom** [comment]
i have not

**Comment by craigburke** [comment]
That's strange. Doing a `jar tf` on both the war and jar files, I see that the generated jar file doesn't contain the assets folder when my plugin is used. Everything is there in the war file though.

**Comment by craigburke** [comment]
@bobbywarner this appears to be work with RC2. Could you confirm that with your test project?

**Comment by bobbywarner** [comment]
@craigburke @davydotcom This is still an issue with Grails 3.0.0.RC2, but it might actually be an issue with Asset-Pipeline-Core as opposed to this plugin... I could have swore it was just happening for Angular templates processes by this plugin last night (using Grails snapshots), but when I try with RC2 today, no assets will work (404s) when building a Jar (./gradlew assemble) and then copying that Jar to another folder.

**Comment by davydotcom** [comment]
Don't think you are supposed to use the jar file

**Comment by craigburke** [comment]
@bobbywarner I see exactly what you mean when using RC1 but RC2 works for me. Would you mind emailing me your test project. I just want to see if there's some difference I'm missing.

@davydotcom I thought with Spring Boot you could use the jar or war file (I might be wrong on that though). I'm wondering if we do find inconsistencies between the war and jar if it's worth raising a JIRA issue.

**Comment by davydotcom** [comment]
its possible you will. asset-pipeline-gradle adds a task "assetCompile". Grails calls this during its build phase. Then these generated assets are copied into either the jar or war file. That last part is the task of the grails gradle plugin so we should verify where its inserting them

**Comment by craigburke** [comment]
@davydotcom how does it determine where it gets inserted?

**Comment by davydotcom** [comment]
we would have to check but it may be using the gradle war plugin to do it not the gradle jar plugin

**Comment by bobbywarner** [comment]
@craigburke You're right, I'm dumb, ha!  I still had my project using 3.0.0.SNAPSHOT.  RC2 works without issues for all assets (including Angular templates with this plugin).

**Comment by davydotcom** [comment]
huzzah!

**Comment by craigburke** [comment]
@bobbywarner I'm glad you reported this. I was unaware there could be differences running the jar outside of the project build folder. Something to verify with newer versions coming out.

Excellent work, gentlemen! :beers: all around!!
