### ISSUE TITLE
Allow for module name default

### ISSUE THREAD

**Issue by mrapczynski** [craigburke/angular-template-asset-pipeline#20]
Working with plugin for the first time. Does not seem to be discovering the module name of my app declared above. Tried it with both unchained _and_ chained method calls styles. Am I missing something?

Attached is a screengrab showing the "_.unminified._" output after the JS was processed.

![screen shot 2015-04-23 at 4 02 41 pm](https://cloud.githubusercontent.com/assets/258614/7309364/7f09d982-e9d2-11e4-8113-4a3478c38fd5.png)

**Comment by mrapczynski** [comment]
Ah, I read your notes more closely and it mentions that the module name is derived from the folders. Can we make this more flexible? Maybe add a config option in the Gradle file to explicitly set a module name if one is not detected through your current approach?

**Comment by craigburke** [comment]
@mrapczynski that seems reasonable especially for the case where you have everything in a single module. I'm curious, what does you directory structure look like currently?

**Comment by mrapczynski** [comment]
@craigburke Very minimal.

![screen shot 2015-04-23 at 5 21 01 pm](https://cloud.githubusercontent.com/assets/258614/7310225/50bb5fe6-e9dd-11e4-88e4-6c8a7b7d3b9b.png)

**Comment by craigburke** [comment]
@mrapczynski alright, I'll work this into the next release (should have time next week).

**Comment by craigburke** [comment]
In thinking about it, it probably makes sense to just add a moduleNameBase property:

```
moduleNameBase: 'fhdaApp'
```

This would handle your particular case, but would still allow for you to put templates in submodules down the road if they are in the appropriate folder. 

For example, a template in the `/ng-views/directives` folder could result in a template being added at **fhdaApp.directives**

**Comment by mrapczynski** [comment]
@craigburke That sounds like a good solution. Your directory handling is nice, and is definitely functionality that should stick around.

For now, I created a cludgy Gradle task that checks the asset output and puts the module name into wherever it is missing from. Looking forward to this update.

**Comment by craigburke** [comment]
Ok, I just published version 2.1.0 with this change. Give it a spin and let me know how it works for you.

**Comment by mrapczynski** [comment]
@craigburke OK, just tried it. No dice.

I configured the plugin like so:

![screen shot 2015-04-28 at 8 50 14 am](https://cloud.githubusercontent.com/assets/258614/7373859/cdce730c-ed83-11e4-9743-13cc8d6a720c.png)

And below is the unminified output - still module name not updated.

![screen shot 2015-04-28 at 8 50 49 am](https://cloud.githubusercontent.com/assets/258614/7373868/d91a286e-ed83-11e4-8ef9-7357b06df918.png)

Am I missing anything?

**Comment by craigburke** [comment]
Hmmm... what kind of app (Grails, spring boot, etc)... did you try a gradle clean?

**Comment by mrapczynski** [comment]
@craigburke Just a plain Gradle Java app with Spring MVC (no Spring Boot). I am building out a template project that my colleagues will clone for training and to create new Angular projects.

To test the 2.1.0 version, I actually had a brand new project where I had not yet done the asset compile. After updating the artifacts, I ran the first build and got the result shown in my last comment.

I'll be working at this most of the day so anything you want to try or debug, I'm up for it.

**Comment by craigburke** [comment]
Would you be able to throw this sample project up on github so I could take a look?

**Comment by mrapczynski** [comment]
@craigburke Yes, here you go: https://github.com/mrapczynski/spring-banner-app-template

Our build refers to an internal Maven repo and some dependencies that will not resolve in Gradle so comment out accordingly

**Comment by craigburke** [comment]
I messed up the docs, the property is **moduleNameBase** not **moduleBaseName.** Does changing that help?

**Comment by mrapczynski** [comment]
@craigburke Sweet! That did it. This is the only issue I had, and it looks fixed. Thanks for all of your help on this.

![screen shot 2015-04-28 at 9 32 01 am](https://cloud.githubusercontent.com/assets/258614/7374860/8469701c-ed89-11e4-96a2-22f41bacfb4e.png)

**Comment by craigburke** [comment]
Awesome! I'm glad you're finding it useful :+1:
