### ISSUE TITLE
Is it possbile to have multiple template folders?

### ISSUE THREAD

**Issue by froilan** [craigburke/angular-template-asset-pipeline#21]
We want to have a project structure like:
- assets/javascripts/
  - featureA
    - templateA.html
    - controllerA.js
  - featureB
    - templateB.html
    - controllerB.js

**Comment by craigburke** [comment]
Yeah it definitely is. 

With the default config settings assuming your template files had the extension `.tpl.html` then templateA.js would look something like this:

```
angular.module('featureA').run(['$templateCache', function($templateCache) {
    $templateCache.put('templateA.html', 'A content');
}]);
```

And templateB.js would be in a separate featureB module:

```
angular.module('featureB').run(['$templateCache', function($templateCache) {
    $templateCache.put('templateB.html', 'B content');
}]);
```

**Comment by froilan** [comment]
Thanks for your reply.

With the default config settings, it is defined to have 'templates' as its folder right?

Does this mean that I have to put my templates inside the templates folder nested inside the featureA and featureB directories? Is there anyway that we can just have it inside featureA and featureB?

**Comment by craigburke** [comment]
No, you don't need to have it in a templates folder. It'll work just fine like that.

**Comment by craigburke** [comment]
I'm going to go ahead and close this issue. Feel free to comment if you have any issues setting it up like that.
