### ISSUE TITLE
configOptions take no effect for Grails 3 in build.gradle

### ISSUE THREAD

**Issue by timofriedlberlin** [craigburke/angular-template-asset-pipeline#22]
I have to use 2.1.0, since the latest Version is compiled with Java 8.

I want to set includePathInName to true, since its not default in that version (build.gradle):

```
assets {
    configOptions = [
        angular : [
            templateFolder: 'templates',
            moduleNameBase: '',
            compressHtml: true,
            preserveHtmlComments: false,
            includePathInName: true
        ]
    ]
}
```

No matter what I change here, it will change nothing. It always loads the template without path

**Comment by timofriedlberlin** [comment]
Okay, figured it out myself, I have to use the grails config in application.yml

```
---
grails:
    assets:
        angular:
            includePathInName: true
```

when is the config used from build.gradle ? I mean its added by Grails 3 automatically ...

**Comment by craigburke** [comment]
@timo-klarshift it's a bit confusing I know. You need them in both places at the moment. The settings in build.gradle are build settings (when building a war or jar) and the application.yml setting are runtime. I think this is something on @davydotcom's list already for the asset pipeline.

**Comment by abobwhite** [comment]
@craigburke Holy cow! I only had the yml version and couldn't figure out why it wasn't working in war mode. What can be done to either document this issue better or to fix it so that it doesn't need to be defined in both places?!
