### ISSUE TITLE
Camel Case

### ISSUE THREAD

**Issue by ctoestreich** [craigburke/angular-template-asset-pipeline#26]
When naming directories using camel case, the toCamelCase is transforming to lower case and breaking module template caches via case dependent pathing.  As a case of irony, the toCamelCase actually destroys camel case.  This is problematic due to the usage module imports through out the site still using the camel case.  A temporary workaround it to lowercase or add - to all module directories, but this creates a disconnect with the actual module names on the other imports and the directory in which they live.

<img width="1242" alt="screen shot 2016-02-25 at 3 37 34 pm" src="https://cloud.githubusercontent.com/assets/691357/13335249/b837e366-dbd5-11e5-948c-162fcf3b59c9.png">

<img width="1348" alt="screen shot 2016-02-25 at 3 35 28 pm" src="https://cloud.githubusercontent.com/assets/691357/13335229/93f02f5e-dbd5-11e5-8fc9-e0bddbf43e86.png">

**Comment by ctoestreich** [comment]
Probably lower case after detecting the existence of dashes or underlines would fix this.

**Comment by ctoestreich** [comment]
Sent over #27

**Comment by ctoestreich** [comment]
Also #28

**Comment by craigburke** [comment]
Yeah, good call. Thanks for the PR.

**Comment by craigburke** [comment]
@ctoestreich I just released 2.2.7 with your fix. Thanks again, man!
