### ISSUE TITLE
Release 2.4.0

### ISSUE THREAD

**Issue by temi** [craigburke/angular-template-asset-pipeline#34]
Hi Craig,

I was after a feature in version 2.4.0. But realised that it has not been published. I am wondering if you plans to release version 2.4.0 soon?

temi

**Comment by craigburke** [comment]
It should have been released. Are you using Grails 2 by chance?

**Comment by temi** [comment]
Yes I am using Grails 2. So it is only available in Grails 3?

**Comment by passionfruit18** [comment]
I would like this feature too for popovers.

**Comment by MarcoZurich** [comment]
Hi,

We also would need release 2.4.0, in order to use the "templateModuleName" property, which has been implemented after the last release 2.3.0 .

Regards,
Marc

**Comment by mainzelM** [comment]
Yes, please release 2.4.0.

Thanks in advance

Martin

**Comment by craigburke** [comment]
Ok, finally got around to this. Sorry about the delay.
